// GET ALL USER_RE LIST
export const GET_ALL_USER_RE = "GET_ALL_USER_RE";
export const GET_ALL_USER_RE_SUCCESS = "GET_ALL_USER_RE_SUCCESS";
export const GET_ALL_USER_RE_FAIL = "GET_ALL_USER_RE_FAIL";

//GET ALL USER_RE WITH STATUS.
export const GET_ALL_USER_RE_WITH_STATUS = "GET_ALL_USER_RE_WITH_STATUS";
export const GET_ALL_USER_RE_WITH_STATUS_SUCCESS =
  "GET_ALL_USER_RE_WITH_STATUS";
export const GET_ALL_USER_RE_WITH_STATUS_FAIL =
  "GET_ALL_USER_RE_WITH_STATUS_FAIL";

// For Creating USER_RE
export const CREATE_USER_RE = "CREATE_USER_RE";
export const CREATE_USER_RE_SUCCESS = "CREATE_USER_RE_SUCCESS";
export const CREATE_USER_RE_FAIL = "CREATE_USER_RE_FAIL";

// For Updating USER_RE Data Status
export const UPDATE_USER_RE = "UPDATE_USER_RE";
export const UPDATE_USER_RE_SUCCESS = "UPDATE_USER_RE_SUCCESS";
export const UPDATE_USER_RE_FAIL = "UPDATE_USER_RE_FAIL";

// For Searching USER_RE
export const SEARCH_USER_RE = "SEARCH_USER_RE";
export const SEARCH_USER_RE_SUCCESS = "SEARCH_USER_RE_SUCCESS";
export const SEARCH_USER_RE_FAIL = "SEARCH_USER_RE_FAIL";

// For Getting USER_RE by USER_REId
export const GET_USER_RE_BY_ID = "GET_USER_RE_BY_ID";
export const GET_USER_RE_BY_ID_SUCCESS = "GET_USER_RE_BY_ID_SUCCESS";
export const GET_USER_RE_BY_ID_FAIL = "GET_USER_RE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_USER_RE = "UPLOAD_ALL_DOCUMENTS_USER_RE";
export const UPLOAD_ALL_DOCUMENTS_USER_RE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_USER_RE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_USER_RE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_USER_RE_FAIL";

//To set API response status
export const CREATE_EDIT_API_USER = "CREATE_EDIT_API_USER";

//GET CHILD USER
export const GET_ALL_CHILD_USER = "GET_ALL_CHILD_USER";
export const GET_ALL_CHILD_USER_SUCCESS = "GET_ALL_CHILD_USER_SUCCESS";
export const GET_ALL_CHILD_USER_FAIL = "GET_ALL_CHILD_USER_FAIL";


export const CREATE_CHILD_AUCTIONEER = "CREATE_CHILD_AUCTIONEER";
export const CREATE_CHILD_AUCTIONEER_SUCCESS = "CREATE_CHILD_AUCTIONEER_SUCCESS";
export const CREATE_CHILD_AUCTIONEER_FAIL = "CREATE_CHILD_AUCTIONEER_FAIL";

export const UPDATE_CHILD_AUCTIONEER = "UPDATE_CHILD_AUCTIONEER";
export const UPDATE_CHILD_AUCTIONEER_SUCCESS = "UPDATE_CHILD_AUCTIONEER_SUCCESS";
export const UPDATE_CHILD_AUCTIONEER_FAIL = "UPDATE_CHILD_AUCTIONEER_FAIL";


export const GET_CHILD_AUCTIONEER_BY_ID = "GET_AUCTIONEER_BY_ID";
export const GET_CHILD_AUCTIONEER_BY_ID_SUCCESS = "GET_CHILD_AUCTIONEER_BY_ID_SUCCESS";
export const GET_CHILD_AUCTIONEER_BY_ID_FAIL = "GET_CHILD_AUCTIONEER_BY_ID_FAIL";