export const GET_ALL_CONFIGURE_PARAMETER = "GET_ALL_CONFIGURE_PARAMETER";
export const GET_ALL_CONFIGURE_PARAMETER_SUCCESS =
  "GET_ALL_CONFIGURE_PARAMETER_SUCCESS";
export const GET_ALL_CONFIGURE_PARAMETER_FAIL =
  "GET_ALL_CONFIGURE_PARAMETER_FAIL";

// For Creating CONFIGURE_PARAMETER
export const CREATE_CONFIGURE_PARAMETER = "CREATE_CONFIGURE_PARAMETER";
export const CREATE_CONFIGURE_PARAMETER_SUCCESS =
  "CREATE_CONFIGURE_PARAMETER_SUCCESS";
export const CREATE_CONFIGURE_PARAMETER_FAIL =
  "CREATE_CONFIGURE_PARAMETER_FAIL";

// For Updating State Data Status
export const UPDATE_CONFIGURE_PARAMETER = "UPDATE_CONFIGURE_PARAMETER";
export const UPDATE_CONFIGURE_PARAMETER_SUCCESS =
  "UPDATE_CONFIGURE_PARAMETER_SUCCESS";
export const UPDATE_CONFIGURE_PARAMETER_FAIL =
  "UPDATE_CONFIGURE_PARAMETER_FAIL";

// For Getting State by stateId
export const GET_CONFIGURE_PARAMETER_BY_ID = "GET_CONFIGURE_PARAMETER_BY_ID";
export const GET_CONFIGURE_PARAMETER_BY_ID_SUCCESS =
  "GET_CONFIGURE_PARAMETER_BY_ID_SUCCESS";
export const GET_CONFIGURE_PARAMETER_BY_ID_FAIL =
  "GET_CONFIGURE_PARAMETER_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM =
  "UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM";
export const UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM_FAIL =
  "UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM_FAIL";

export const CREATE_EDIT_CONFIGURE_PARAMETER_API_STATUS =
  "CREATE_EDIT_CONFIGURE_PARAMETER_API_STATUS";



// ENGLISH AUCTION ACTION LABELS
export const FETCH_PRICE_RANGE_REQUEST = "FETCH_PRICE_RANGE_REQUEST";
export const FETCH_PRICE_RANGE_SUCCESS = "FETCH_PRICE_RANGE_SUCCESS";
export const FETCH_PRICE_RANGE_FAILURE = "FETCH_PRICE_RANGE_FAILURE";


export const CREATE_AUCTION_REQUEST = 'CREATE_AUCTION_REQUEST';
export const CREATE_AUCTION_SUCCESS = 'CREATE_AUCTION_SUCCESS';
export const CREATE_AUCTION_FAILURE = 'CREATE_AUCTION_FAILURE';



export const FETCH_AUCTION_DATA_REQUEST = "FETCH_AUCTION_DATA_REQUEST";
export const FETCH_AUCTION_DATA_SUCCESS = "FETCH_AUCTION_DATA_SUCCESS";
export const FETCH_AUCTION_DATA_FAILURE = "FETCH_AUCTION_DATA_FAILURE";

export const FETCH_AUCTION_DATA_OPTION_REQUEST = "FETCH_AUCTION_DATA_OPTION_REQUEST";
export const FETCH_AUCTION_DATA_OPTION_SUCCESS = "FETCH_AUCTION_DATA_OPTION_SUCCESS";
export const FETCH_AUCTION_DATA_OPTION_FAILURE = "FETCH_AUCTION_DATA_OPTION_FAILURE";

