export const GET_ALL_PACKAGE_TYPE = "GET_ALL_PACKAGE_TYPE";
export const GET_ALL_PACKAGE_TYPE_SUCCESS = "GET_ALL_PACKAGE_TYPE_SUCCESS";
export const GET_ALL_PACKAGE_TYPE_FAIL = "GET_ALL_PACKAGE_TYPE_FAIL";

// For Creating MARK
export const CREATE_PACKAGE_TYPE = "CREATE_PACKAGE_TYPE";
export const CREATE_PACKAGE_TYPE_SUCCESS = "CREATE_PACKAGE_TYPE_SUCCESS";
export const CREATE_PACKAGE_TYPE_FAIL = "CREATE_PACKAGE_TYPE_FAIL";

// For Updating State Data Status
export const UPDATE_PACKAGE_TYPE = "UPDATE_PACKAGE_TYPE";
export const UPDATE_PACKAGE_TYPE_SUCCESS = "UPDATE_PACKAGE_TYPE_SUCCESS";
export const UPDATE_PACKAGE_TYPE_FAIL = "UPDATE_PACKAGE_TYPE_FAIL";

// For Getting State by stateId
export const GET_PACKAGE_TYPE_BY_ID = "GET_PACKAGE_TYPE_BY_ID";
export const GET_PACKAGE_TYPE_BY_ID_SUCCESS = "GET_PACKAGE_TYPE_BY_ID_SUCCESS";
export const GET_PACKAGE_TYPE_BY_ID_FAIL = "GET_PACKAGE_TYPE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_PACKAGE_TYPE = "UPLOAD_ALL_DOCUMENTS_PACKAGE_TYPE";
export const UPLOAD_ALL_DOCUMENTS_PACKAGE_TYPE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_PACKAGE_TYPE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_PACKAGE_TYPE_FAIL = "UPLOAD_ALL_DOCUMENTS_PACKAGE_TYPE_FAIL";

export const GET_ALL_PACKAGE_TYPE_WITHOUT_FILTER = "GET_ALL_PACKAGE_TYPE_WITHOUT_FILTER";
export const GET_ALL_PACKAGE_TYPE_WITHOUT_FILTER_SUCCESS =
  "GET_ALL_PACKAGE_TYPE_WITHOUT_FILTER_SUCCESS";
export const GET_ALL_PACKAGE_TYPE_WITHOUT_FILTER_FAIL =
  "GET_ALL_PACKAGE_TYPE_WITHOUT_FILTER_FAIL";

  export const CREATE_EDIT_API_STATUS_PACKAGE_TYPE = "CREATE_EDIT_API_STATUS_PACKAGE_TYPE";
