export const GET_ALL_PACKAGE_SIZE = "GET_ALL_PACKAGE_SIZE";
export const GET_ALL_PACKAGE_SIZE_SUCCESS = "GET_ALL_PACKAGE_SIZE_SUCCESS";
export const GET_ALL_PACKAGE_SIZE_FAIL = "GET_ALL_PACKAGE_SIZE_FAIL";

// For Creating MARK
export const CREATE_PACKAGE_SIZE = "CREATE_PACKAGE_SIZE";
export const CREATE_PACKAGE_SIZE_SUCCESS = "CREATE_PACKAGE_SIZE_SUCCESS";
export const CREATE_PACKAGE_SIZE_FAIL = "CREATE_PACKAGE_SIZE_FAIL";

// For Updating State Data Status
export const UPDATE_PACKAGE_SIZE = "UPDATE_PACKAGE_SIZE";
export const UPDATE_PACKAGE_SIZE_SUCCESS = "UPDATE_PACKAGE_SIZE_SUCCESS";
export const UPDATE_PACKAGE_SIZE_FAIL = "UPDATE_PACKAGE_SIZE_FAIL";

// For Getting State by stateId
export const GET_PACKAGE_SIZE_BY_ID = "GET_PACKAGE_SIZE_BY_ID";
export const GET_PACKAGE_SIZE_BY_ID_SUCCESS = "GET_PACKAGE_SIZE_BY_ID_SUCCESS";
export const GET_PACKAGE_SIZE_BY_ID_FAIL = "GET_PACKAGE_SIZE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_PACKAGE_SIZE = "UPLOAD_ALL_DOCUMENTS_PACKAGE_SIZE";
export const UPLOAD_ALL_DOCUMENTS_PACKAGE_SIZE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_PACKAGE_SIZE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_PACKAGE_SIZE_FAIL = "UPLOAD_ALL_DOCUMENTS_PACKAGE_SIZE_FAIL";

export const GET_ALL_PACKAGE_SIZE_WITHOUT_FILTER = "GET_ALL_PACKAGE_SIZE_WITHOUT_FILTER";
export const GET_ALL_PACKAGE_SIZE_WITHOUT_FILTER_SUCCESS =
  "GET_ALL_PACKAGE_SIZE_WITHOUT_FILTER_SUCCESS";
export const GET_ALL_PACKAGE_SIZE_WITHOUT_FILTER_FAIL =
  "GET_ALL_PACKAGE_SIZE_WITHOUT_FILTER_FAIL";

  export const CREATE_EDIT_API_STATUS_PACKAGE_SIZE = "CREATE_EDIT_API_STATUS_PACKAGE_SIZE";
