// GET ALL USER LIST
export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

//GET ALL USER WITH STATUS.
export const GET_ALL_USER_WITH_STATUS = "GET_ALL_USER_WITH_STATUS";
export const GET_ALL_USER_WITH_STATUS_SUCCESS = "GET_ALL_USER_WITH_STATUS";
export const GET_ALL_USER_WITH_STATUS_FAIL = "GET_ALL_USER_WITH_STATUS_FAIL";

// For Creating USER
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

// For Updating USER Data Status
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

// For Searching USER
export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL";

// For Getting USER by USERId
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL";

//To set API response status
export const CREATE_EDIT_API_USERRGG = "CREATE_EDIT_API_USERRGG";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_USER = "UPLOAD_ALL_DOCUMENTS_USER";
export const UPLOAD_ALL_DOCUMENTS_USER_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_USER_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_USER_FAIL = "UPLOAD_ALL_DOCUMENTS_USER_FAIL";
