export const GET_ALL_GRACE = "GET_ALL_GRACE";
export const GET_ALL_GRACE_SUCCESS = "GET_ALL_GRACE_SUCCESS";
export const GET_ALL_GRACE_FAIL = "GET_ALL_GRACE_FAIL";

// For Creating MARK
export const CREATE_GRACE = "CREATE_GRACE";
export const CREATE_GRACE_SUCCESS = "CREATE_GRACE_SUCCESS";
export const CREATE_GRACE_FAIL = "CREATE_GRACE_FAIL";

// For Updating State Data Status
export const UPDATE_GRACE = "UPDATE_GRACE";
export const UPDATE_GRACE_SUCCESS = "UPDATE_GRACE_SUCCESS";
export const UPDATE_GRACE_FAIL = "UPDATE_GRACE_FAIL";

// For Getting State by stateId
export const GET_GRACE_BY_ID = "GET_GRACE_BY_ID";
export const GET_GRACE_BY_ID_SUCCESS = "GET_GRACE_BY_ID_SUCCESS";
export const GET_GRACE_BY_ID_FAIL = "GET_GRACE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_GRACE = "UPLOAD_ALL_DOCUMENTS_GRACE";
export const UPLOAD_ALL_DOCUMENTS_GRACE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_GRACE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_GRACE_FAIL = "UPLOAD_ALL_DOCUMENTS_GRACE_FAIL";

export const GET_ALL_GRACE_WITHOUT_FILTER = "GET_ALL_GRACE_WITHOUT_FILTER";
export const GET_ALL_GRACE_WITHOUT_FILTER_SUCCESS =
  "GET_ALL_GRACE_WITHOUT_FILTER_SUCCESS";
export const GET_ALL_GRACE_WITHOUT_FILTER_FAIL =
  "GET_ALL_GRACE_WITHOUT_FILTER_FAIL";

  export const GET_ALL_SALENO_PREAUCTION = "GET_ALL_SALENO_PREAUCTION_PREAUCTION";
  export const GET_ALL_SALENO_PREAUCTION_SUCCESS = "GET_ALL_SALENO_PREAUCTION_SUCCESS";
  export const GET_ALL_SALENO_PREAUCTION_FAIL = "GET_ALL_SALENO_PREAUCTION_FAIL";


export const CREATE_EDIT_API_STATUS_GRACE = "CREATE_EDIT_API_STATUS_GRACE";