// GET ALL TAO_USER LIST
export const GET_ALL_RULE_ENGINE = "GET_ALL_RULE_ENGINE";
export const GET_ALL_RULE_ENGINE_SUCCESS = "GET_ALL_RULE_ENGINE_SUCCESS";
export const GET_ALL_RULE_ENGINE_FAIL = "GET_ALL_RULE_ENGINE_FAIL";

//GET ALL TAO_USER WITH STATUS.
export const GET_ALL_RULE_ENGINE_WITH_STATUS =
  "GET_ALL_RULE_ENGINE_WITH_STATUS";
export const GET_ALL_RULE_ENGINE_WITH_STATUS_SUCCESS =
  "GET_ALL_RULE_ENGINE_WITH_STATUS";
export const GET_ALL_RULE_ENGINE_WITH_STATUS_FAIL =
  "GET_ALL_RULE_ENGINE_WITH_STATUS_FAIL";

// For Creating TAO_USER
export const CREATE_RULE_ENGINE = "CREATE_RULE_ENGINE";
export const CREATE_RULE_ENGINE_SUCCESS = "CREATE_RULE_ENGINE_SUCCESS";
export const CREATE_RULE_ENGINE_FAIL = "CREATE_RULE_ENGINE_FAIL";

// For Updating TAO_USER Data Status
export const UPDATE_RULE_ENGINE = "UPDATE_RULE_ENGINE";
export const UPDATE_RULE_ENGINE_SUCCESS = "UPDATE_RULE_ENGINE_SUCCESS";
export const UPDATE_RULE_ENGINE_FAIL = "UPDATE_RULE_ENGINE_FAIL";

// For Searching TAO_USER
export const SEARCH_RULE_ENGINE = "SEARCH_RULE_ENGINE";
export const SEARCH_RULE_ENGINE_SUCCESS = "SEARCH_RULE_ENGINE_SUCCESS";
export const SEARCH_RULE_ENGINE_FAIL = "SEARCH_RULE_ENGINE_FAIL";

// For Getting TAO_USER by TAO_USERId
export const GET_RULE_ENGINE_BY_ID = "GET_RULE_ENGINE_BY_ID";
export const GET_RULE_ENGINE_BY_ID_SUCCESS = "GET_RULE_ENGINE_BY_ID_SUCCESS";
export const GET_RULE_ENGINE_BY_ID_FAIL = "GET_RULE_ENGINE_BY_ID_FAIL";

//To set API response status
export const CREATE_EDIT_API_RULE_ENGINE = "CREATE_EDIT_API_RULE_ENGINE";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_RULE_ENGINE =
  "UPLOAD_ALL_DOCUMENTS_RULE_ENGINE";
export const UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_FAIL";
