// GET ALL TAO_USER LIST
export const GET_ALL_TAO_USER = "GET_ALL_TAO_USER";
export const GET_ALL_TAO_USER_SUCCESS = "GET_ALL_TAO_USER_SUCCESS";
export const GET_ALL_TAO_USER_FAIL = "GET_ALL_TAO_USER_FAIL";

//GET ALL TAO_USER WITH STATUS.
export const GET_ALL_TAO_USER_WITH_STATUS = "GET_ALL_TAO_USER_WITH_STATUS";
export const GET_ALL_TAO_USER_WITH_STATUS_SUCCESS =
  "GET_ALL_TAO_USER_WITH_STATUS";
export const GET_ALL_TAO_USER_WITH_STATUS_FAIL =
  "GET_ALL_TAO_USER_WITH_STATUS_FAIL";

// For Creating TAO_USER
export const CREATE_TAO_USER = "CREATE_TAO_USER";
export const CREATE_TAO_USER_SUCCESS = "CREATE_TAO_USER_SUCCESS";
export const CREATE_TAO_USER_FAIL = "CREATE_TAO_USER_FAIL";

// For Updating TAO_USER Data Status
export const UPDATE_TAO_USER = "UPDATE_TAO_USER";
export const UPDATE_TAO_USER_SUCCESS = "UPDATE_TAO_USER_SUCCESS";
export const UPDATE_TAO_USER_FAIL = "UPDATE_TAO_USER_FAIL";

// For Searching TAO_USER
export const SEARCH_TAO_USER = "SEARCH_TAO_USER";
export const SEARCH_TAO_USER_SUCCESS = "SEARCH_TAO_USER_SUCCESS";
export const SEARCH_TAO_USER_FAIL = "SEARCH_TAO_USER_FAIL";

// For Getting TAO_USER by TAO_USERId
export const GET_TAO_USER_BY_ID = "GET_TAO_USER_BY_ID";
export const GET_TAO_USER_BY_ID_SUCCESS = "GET_TAO_USER_BY_ID_SUCCESS";
export const GET_TAO_USER_BY_ID_FAIL = "GET_TAO_USER_BY_ID_FAIL";

//To set API response status
export const CREATE_EDIT_API_TAO_USERRGG = "CREATE_EDIT_API_TAO_USERRGG";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_TAO_USER = "UPLOAD_ALL_DOCUMENTS_TAO_USER";
export const UPLOAD_ALL_DOCUMENTS_TAO_USER_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_TAO_USER_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_TAO_USER_FAIL =
  "UPLOAD_ALL_DOCUMENTS_TAO_USER_FAIL";
