export const FETCH_USER_RIGHTS_REQUEST = 'FETCH_USER_RIGHTS_REQUEST';
export const FETCH_USER_RIGHTS_SUCCESS = 'FETCH_USER_RIGHTS_SUCCESS';
export const FETCH_USER_RIGHTS_FAILURE = 'FETCH_USER_RIGHTS_FAILURE';