// GET ALL TAO_USER LIST
export const GET_ALL_RULE_ENGINE_ENG = "GET_ALL_RULE_ENGINE_ENG";
export const GET_ALL_RULE_ENGINE_ENG_SUCCESS =
  "GET_ALL_RULE_ENGINE_ENG_SUCCESS";
export const GET_ALL_RULE_ENGINE_ENG_FAIL = "GET_ALL_RULE_ENGINE_ENG_FAIL";

export const GET_ALL_RULE_ENGINE_BRT = "GET_ALL_RULE_ENGINE_BRT";
export const GET_ALL_RULE_ENGINE_BRT_SUCCESS =
  "GET_ALL_RULE_ENGINE_BRT_SUCCESS";
export const GET_ALL_RULE_ENGINE_BRT_FAIL = "GET_ALL_RULE_ENGINE_BRT_FAIL";

//GET ALL TAO_USER WITH STATUS.
export const GET_ALL_RULE_ENGINE_ENG_WITH_STATUS =
  "GET_ALL_RULE_ENGINE_ENG_WITH_STATUS";
export const GET_ALL_RULE_ENGINE_ENG_WITH_STATUS_SUCCESS =
  "GET_ALL_RULE_ENGINE_ENG_WITH_STATUS";
export const GET_ALL_RULE_ENGINE_ENG_WITH_STATUS_FAIL =
  "GET_ALL_RULE_ENGINE_ENG_WITH_STATUS_FAIL";

// For Creating TAO_USER
export const CREATE_RULE_ENGINE_ENG = "CREATE_RULE_ENGINE_ENG";
export const CREATE_RULE_ENGINE_ENG_SUCCESS = "CREATE_RULE_ENGINE_ENG_SUCCESS";
export const CREATE_RULE_ENGINE_ENG_FAIL = "CREATE_RULE_ENGINE_ENG_FAIL";

// For Updating TAO_USER Data Status
export const UPDATE_RULE_ENGINE_ENG = "UPDATE_RULE_ENGINE_ENG";
export const UPDATE_RULE_ENGINE_ENG_SUCCESS = "UPDATE_RULE_ENGINE_ENG_SUCCESS";
export const UPDATE_RULE_ENGINE_ENG_FAIL = "UPDATE_RULE_ENGINE_ENG_FAIL";

// For Searching TAO_USER
export const SEARCH_RULE_ENGINE_ENG = "SEARCH_RULE_ENGINE_ENG";
export const SEARCH_RULE_ENGINE_ENG_SUCCESS = "SEARCH_RULE_ENGINE_ENG_SUCCESS";
export const SEARCH_RULE_ENGINE_ENG_FAIL = "SEARCH_RULE_ENGINE_ENG_FAIL";

// For Getting TAO_USER by TAO_USERId
export const GET_RULE_ENGINE_ENG_BY_ID = "GET_RULE_ENGINE_ENG_BY_ID";
export const GET_RULE_ENGINE_ENG_BY_ID_SUCCESS =
  "GET_RULE_ENGINE_ENG_BY_ID_SUCCESS";
export const GET_RULE_ENGINE_ENG_BY_ID_FAIL = "GET_RULE_ENGINE_ENG_BY_ID_FAIL";

//To set API response status
export const CREATE_EDIT_API_RULE_ENGINE_ENG =
  "CREATE_EDIT_API_RULE_ENGINE_ENG";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_ENG =
  "UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_ENG";
export const UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_ENG_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_ENG_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_ENG_FAIL =
  "UPLOAD_ALL_DOCUMENTS_RULE_ENGINE_ENG_FAIL";
