export const GET_ALL_BUYER = "GET_ALL_BUYER";
export const GET_ALL_BUYER_SUCCESS = "GET_ALL_BUYER_SUCCESS";
export const GET_ALL_BUYER_FAIL = "GET_ALL_BUYER_FAIL";

export const GET_ALL_PAYMENT = "GET_ALL_PAYMENT";
export const GET_ALL_PAYMENT_SUCCESS = "GET_ALL_PAYMENT_SUCCESS";
export const GET_ALL_PAYMENT_FAIL = "GET_ALL_PAYMENT_FAIL";

// For Creating BUYER
export const CREATE_BUYER = "CREATE_BUYER";
export const CREATE_BUYER_SUCCESS = "CREATE_BUYER_SUCCESS";
export const CREATE_BUYER_FAIL = "CREATE_BUYER_FAIL";

export const CREATE_CHILD_BUYER = "CREATE_CHILD_BUYER";
export const CREATE_CHILD_BUYER_SUCCESS = "CREATE_CHILD_BUYER_SUCCESS";
export const CREATE_CHILD_BUYER_FAIL = "CREATE_CHILD_BUYER_FAIL";

// For Updating State Data Status
export const UPDATE_BUYER = "UPDATE_BUYER";
export const UPDATE_BUYER_SUCCESS = "UPDATE_BUYER_SUCCESS";
export const UPDATE_BUYER_FAIL = "UPDATE_BUYER_FAIL";

export const UPDATE_CHILD_BUYER = "UPDATE_CHILD_BUYER";
export const UPDATE_CHILD_BUYER_SUCCESS = "UPDATE_CHILD_BUYER_SUCCESS";
export const UPDATE_CHILD_BUYER_FAIL = "UPDATE_CHILD_BUYER_FAIL";

// For Getting State by stateId
export const GET_BUYER_BY_ID = "GET_BUYER_BY_ID";
export const GET_BUYER_BY_ID_SUCCESS = "GET_BUYER_BY_ID_SUCCESS";
export const GET_BUYER_BY_ID_FAIL = "GET_BUYER_BY_ID_FAIL";
// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_BUYER = "UPLOAD_ALL_DOCUMENTS_BUYER";
export const UPLOAD_ALL_DOCUMENTS_BUYER_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_BUYER_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_BUYER_FAIL =
  "UPLOAD_ALL_DOCUMENTS_BUYER_FAIL";
//GET CHILD USER
export const GET_ALL_CHILD_BUYER = "GET_ALL_CHILD_BUYER";
export const GET_ALL_CHILD_BUYER_SUCCESS = "GET_ALL_CHILD_BUYER_SUCCESS";
export const GET_ALL_CHILD_BUYER_FAIL = "GET_ALL_CHILD_BUYER_FAIL";

export const GET_CHILD_BUYER_BY_ID = "GET_BUYER_BY_ID";
export const GET_CHILD_BUYER_BY_ID_SUCCESS = "GET_CHILD_BUYER_BY_ID_SUCCESS";
export const GET_CHILD_BUYER_BY_ID_FAIL = "GET_CHILD_BUYER_BY_ID_FAIL";

export const CREATE_EDIT_API_STATUS_BUYER = "CREATE_EDIT_API_STATUS_BUYER";
export const CLOSE_MODEL = "CLOSE_MODEL";
export const CHILD_CREATE_EDIT_API_STATUS_BUYER =
  "CHILD_CREATE_EDIT_API_STATUS_BUYER";
