export const FETCH_AUCTION_SEARCH_BID_BOOK_DATA =
  "FETCH_AUCTION_SEARCH_BID_BOOK_DATA";
export const FETCH_AUCTION_SEARCH_BID_BOOK_DATA_SUCCESS =
  "FETCH_AUCTION_SEARCH_BID_BOOK_DATA_SUCCESS";
export const FETCH_AUCTION_SEARCH_BID_BOOK_DATA_FAILURE =
  "FETCH_AUCTION_SEARCH_BID_BOOK_DATA_FAILURE";
